CREATE TABLE car_models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   model VARCHAR(50) NOT NULL,
   manufacturer_id BIGINT NOT NULL,
   seats INTEGER NOT NULL,
   fuel_type VARCHAR(20) NOT NULL,
   transmission_type VARCHAR(20) NOT NULL,
   CONSTRAINT pk_car_models PRIMARY KEY (id)
);

CREATE TABLE car_sharing_companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(30) NOT NULL,
   description VARCHAR(200) NOT NULL,
   address VARCHAR(50) NOT NULL,
   CONSTRAINT pk_car_sharing_companies PRIMARY KEY (id)
);

CREATE TABLE manufacturers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(50) NOT NULL,
   CONSTRAINT pk_manufacturers PRIMARY KEY (id)
);

CREATE TABLE registered_cars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   license_plate_number VARCHAR(30) NOT NULL,
   car_sharing_company_id BIGINT NOT NULL,
   car_model_id BIGINT NOT NULL,
   price_per_minute DECIMAL(8, 2) NOT NULL,
   is_available BOOLEAN NOT NULL,
   car_location_latitude DOUBLE PRECISION,
   car_location_longitude DOUBLE PRECISION,
   CONSTRAINT pk_registered_cars PRIMARY KEY (id)
);

CREATE TABLE support_phones (
  car_sharing_company_id BIGINT NOT NULL,
   support_phone VARCHAR(30) NOT NULL
);

ALTER TABLE car_models ADD CONSTRAINT FK_CAR_MODELS_ON_MANUFACTURER FOREIGN KEY (manufacturer_id) REFERENCES manufacturers (id);

ALTER TABLE registered_cars ADD CONSTRAINT FK_REGISTERED_CARS_ON_CAR_MODEL FOREIGN KEY (car_model_id) REFERENCES car_models (id);

ALTER TABLE registered_cars ADD CONSTRAINT FK_REGISTERED_CARS_ON_CAR_SHARING_COMPANY FOREIGN KEY (car_sharing_company_id) REFERENCES car_sharing_companies (id);

ALTER TABLE support_phones ADD CONSTRAINT fk_support_phones_on_car_sharing_company FOREIGN KEY (car_sharing_company_id) REFERENCES car_sharing_companies (id);